version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: employees
    environment:
      POSTGRES_DB: employees
      POSTGRES_PASSWORD: employees
      POSTGRES_USER: employees
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    ports:
      - 5432:5432
